server:
  port: 8080

elasticSearchEnabled: true
elasticSearchHost: ${elasticsearch.host:localhost}
elasticSearchIndex: ${elasticsearch.index:articles}
elasticSearchType: ${elasticsearch.type:article}

elasticSearchNafMapping:
  # author:
  creationTime: dateRetrieved
  # fileName:
  # fileType:
  language: language
  location: outletCountry
  magazine: outletName
  # naf: naf
  # pages:
  publisher: ownerName
  rawText: text
  section: category
  title: title

eureka:
 client:
  enabled: true
  serviceUrl:
   defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/
 instance:
    statusPageUrlPath: /
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  file: source-http-naf.log
  level: 
    com.langstok: debug
    