server:
  port: 8080

elasticsearch:
   host: ${langstok.nlp.elasticsearch.host:localhost}

document:
   index: ${langstok.nlp.elasticsearch.index:nlp}
   type: ${langstok.nlp.elasticsearch.type:kaf}

logging:
  file: source-http-naf.log
  level: 
    com.langstok: debug
    