server:
  port: 8080

elasticsearch:
   host: ${langstok.nlp.elasticsearch.host:localhost}

document:
   index: ${langstok.nlp.elasticsearch.index:articles}
   type: ${langstok.nlp.elasticsearch.type:article}

naf:
   mapping:
       # author:
       creationTime: dateRetrieved
       fileName: url
       # fileType:
       language: language
       location: outletCountry
       magazine: outletName
       # naf: naf
       # pages:
       publisher: ownerName
       rawText: text
       section: category
       title: title
       uri: uri

eureka:
 client:
  enabled: true
  serviceUrl:
   defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/
 instance:
    statusPageUrlPath: /
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  file: source-http-naf.log
  level: 
    com.langstok: debug
    